import { useState, useRef, useCallback, useEffect } from 'react'

// All /api/* requests are proxied to VITE_API_BASE by Vite (see vite.config.js).
// Never set API_BASE here — always use relative paths so the proxy works.
async function queryLegal(question, topK = 5) {
  const res = await fetch('/api/query', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ question, top_k: topK }),
  })
  if (!res.ok) {
    const err = await res.json().catch(() => ({}))
    throw new Error(err.detail ?? `HTTP ${res.status}`)
  }
  return res.json()
}

const SAMPLES = [
  'लोक सेवा आयोगको मुख्य काम के हो?',
  'श्रम ऐन अनुसार कामदारलाई कति बिदा पाइन्छ?',
  'बालबालिका ऐनले बाल श्रम सम्बन्धमा के भन्छ?',
  'सम्बन्ध विच्छेद कसरी प्राप्त गर्ने?',
  'नागरिकको मौलिक हक के हो?',
]

function Spinner({ size = 'sm' }) {
  const cls = size === 'lg' ? 'w-8 h-8 border-[3px]' : 'w-4 h-4 border-2'
  return <span className={`${cls} rounded-full border-purple-200 border-t-purple-600 animate-spin inline-block flex-shrink-0`} />
}

function ChevronIcon({ open }) {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"
      strokeLinecap="round" strokeLinejoin="round"
      style={{ transform: open ? 'rotate(180deg)' : 'rotate(0deg)', transition: 'transform 0.2s ease' }}>
      <polyline points="6 9 12 15 18 9" />
    </svg>
  )
}

function Collapsible({ badge, badgeClass, label, children, defaultOpen = false }) {
  const [open, setOpen] = useState(defaultOpen)
  return (
    <div className="rounded-xl border border-purple-100 overflow-hidden bg-white shadow-sm">
      <button
        onClick={() => setOpen(o => !o)}
        className="w-full flex items-center gap-3 px-4 py-3 hover:bg-purple-50/60 transition-colors text-left"
      >
        <span className={`text-[10px] font-bold tracking-widest uppercase px-2 py-0.5 rounded-md border flex-shrink-0 ${badgeClass}`}>
          {badge}
        </span>
        <span className="text-xs font-medium text-gray-600 flex-1">{label}</span>
        <span className="text-gray-300 flex-shrink-0"><ChevronIcon open={open} /></span>
      </button>
      {open && <div className="border-t border-purple-50">{children}</div>}
    </div>
  )
}

function HydeCard({ passage }) {
  return (
    <Collapsible
	  badge="hyde"
      badgeClass="bg-blue-50 text-blue-600 border-blue-100"
      label="Hypothetical passage generated by SLM — used as retrieval query"
    >
      <div className="p-4 bg-gray-50/50">
        <p className="font-mono text-[11px] leading-relaxed text-gray-500 whitespace-pre-wrap">{passage}</p>
      </div>
    </Collapsible>
  )
}

function DocsCard({ docs }) {
  const [expanded, setExpanded] = useState(null)
  return (
    <Collapsible
	  badge="context"
      badgeClass="bg-emerald-50 text-emerald-600 border-emerald-100"
      label={`${docs.length} legal passages retrieved from FAISS index`}
    >
      <div className="divide-y divide-purple-50">
        {docs.map((doc, i) => (
          <div key={i}>
            <button
              onClick={() => setExpanded(expanded === i ? null : i)}
              className="w-full flex items-center gap-3 px-4 py-2.5 hover:bg-purple-50/40 transition-colors text-left"
            >
              <span className="w-5 h-5 rounded-full bg-emerald-100 text-emerald-700 text-[10px] font-bold flex items-center justify-center flex-shrink-0">
                {i + 1}
              </span>
              <span className="text-xs text-gray-400 truncate flex-1 font-mono">
                {doc.slice(0, 90).replace(/\n/g, ' ')}…
              </span>
              <span className="text-gray-300 flex-shrink-0"><ChevronIcon open={expanded === i} /></span>
            </button>
            {expanded === i && (
              <div className="px-4 pb-3 pl-12">
                <p className="font-mono text-[11px] leading-relaxed text-gray-500 whitespace-pre-wrap bg-white rounded-lg p-3 border border-purple-100">
                  {doc}
                </p>
              </div>
            )}
          </div>
        ))}
      </div>
    </Collapsible>
  )
}

function AnswerCard({ answer }) {
  return (
    <div className="rounded-xl overflow-hidden border border-purple-200 shadow-md shadow-purple-100 bg-white">
      <div className="flex items-center gap-3 px-4 py-3 bg-gradient-to-r from-purple-600 to-violet-600">
        <span className="text-[10px] font-bold tracking-widest uppercase px-2 py-0.5 rounded-md bg-white/20 text-white border border-white/25 flex-shrink-0">
	      answer
        </span>
        <span className="text-xs font-medium text-white/90">Legal response grounded in retrieved context</span>
        <svg className="ml-auto flex-shrink-0" width="14" height="14" viewBox="0 0 24 24" fill="white" opacity="0.5">
          <path d="M12 2l2.4 7.6H22l-6.2 4.5 2.4 7.5L12 17.1l-6.2 4.5 2.4-7.5L2 9.6h7.6z"/>
        </svg>
      </div>
      <div className="p-5">
        <p className="text-sm leading-[1.9] text-gray-800 whitespace-pre-wrap">{answer}</p>
      </div>
    </div>
  )
}

function PipelineStep({ num, label, status }) {
  const ring = {
    waiting: 'w-8 h-8 rounded-full border-2 border-gray-200 bg-white text-gray-300 text-xs font-semibold flex items-center justify-center flex-shrink-0',
    active:  'w-8 h-8 rounded-full border-2 border-purple-600 bg-purple-600 text-white text-xs font-semibold flex items-center justify-center flex-shrink-0 shadow-lg shadow-purple-200',
    done:    'w-8 h-8 rounded-full border-2 border-emerald-500 bg-emerald-500 text-white text-xs font-semibold flex items-center justify-center flex-shrink-0',
  }[status]
  const lbl = {
    waiting: 'text-[11px] text-gray-300 text-center leading-tight',
    active:  'text-[11px] text-purple-600 font-semibold text-center leading-tight',
    done:    'text-[11px] text-emerald-600 text-center leading-tight',
  }[status]
  return (
    <div className="flex flex-col items-center gap-2">
	  <div className={ring}>{num}</div>
      <span className={lbl}>{label}</span>
    </div>
  )
}

function LoadingView({ phase }) {
  const idx = ['hyde', 'retrieve', 'answer'].indexOf(phase)
  const st = (i) => i < idx ? 'done' : i === idx ? 'active' : 'waiting'
  const line = (active) => (
    <div className="flex-1 flex items-start pt-4">
      <div className={`h-px w-full transition-colors duration-500 ${active ? 'bg-purple-300' : 'bg-gray-150'}`} />
    </div>
  )
  return (
    <div className="bg-white rounded-2xl border border-purple-100 px-8 py-10 text-center shadow-sm">
      <div className="flex justify-center mb-5"><Spinner size="lg" /></div>
      <p className="text-sm font-semibold text-gray-700 mb-1">Processing your query</p>
      <p className="text-xs text-gray-400 mb-8">Running the HyDE + RAG pipeline</p>
      <div className="flex items-start gap-2 max-w-sm mx-auto">
        <PipelineStep num="1" label="Generate HyDE" status={st(0)} />
        {line(idx >= 1)}
        <PipelineStep num="2" label="Search FAISS" status={st(1)} />
        {line(idx >= 2)}
        <PipelineStep num="3" label="Generate answer" status={st(2)} />
      </div>
    </div>
  )
}

export default function App() {
  const [question, setQuestion] = useState('')
  const [loading, setLoading]   = useState(false)
  const [phase, setPhase]       = useState('hyde')
  const [result, setResult]     = useState(null)
  const [error, setError]       = useState(null)
  const [history, setHistory]   = useState([])
  const textareaRef             = useRef(null)
  const resultsRef              = useRef(null)
  const mode = 'single'

  useEffect(() => {
    const ta = textareaRef.current
    if (!ta) return
    ta.style.height = 'auto'
    ta.style.height = Math.min(ta.scrollHeight, 160) + 'px'
  }, [question])

  const handleSubmit = useCallback(async (q = question) => {
    const trimmed = q.trim()
    if (!trimmed || loading) return
    setQuestion(trimmed)
    setLoading(true); setError(null); setResult(null); setPhase('hyde')
    const t1 = setTimeout(() => setPhase('retrieve'), 3000)
    const t2 = setTimeout(() => setPhase('answer'), 7000)
    try {
      const data = await queryLegal(trimmed)
      setResult(data)
      clearTimeout(t1); clearTimeout(t2)
      setHistory(h => [{ question: trimmed, time: new Date().toLocaleTimeString() }, ...h].slice(0, 6))
      setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 100)
    } catch (e) {
      clearTimeout(t1); clearTimeout(t2)
      setError(e.message)
    } finally {
      setLoading(false)
    }
  }, [question, loading])

  const handleKey = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleSubmit() }
  }

  return (
    <div className="min-h-screen bg-[#f8f7ff] flex flex-col">
      <header className="bg-white border-b border-purple-100 sticky top-0 z-10 shadow-sm shadow-purple-50">
        <div className="max-w-5xl mx-auto px-5 h-14 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-purple-600 flex items-center justify-center text-white flex-shrink-0">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
                <path d="M12 1L3 5v6c0 5.25 3.75 10.15 9 11.35C17.25 21.15 21 16.25 21 11V5L12 1z"/>
              </svg>
            </div>
            <span className="text-sm font-semibold text-gray-900">नेपाली कानूनी सहायक</span>
            <span className="hidden sm:block text-xs text-gray-300">/ Nepali Legal AI</span>
          </div>
          <div className="flex items-center gap-1.5 text-[11px] text-purple-500 font-medium bg-purple-50 border border-purple-100 rounded-full px-3 py-1">
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
            <span className="hidden sm:block">HyDE · FAISS · Qwen2.5</span>
          </div>
        </div>
      </header>

      <div className="flex-1 max-w-5xl mx-auto w-full px-4 sm:px-5 py-6 grid grid-cols-1 lg:grid-cols-[240px_1fr] gap-5 items-start">
        <aside className="space-y-4 lg:sticky lg:top-20">
          <div className="rounded-2xl bg-gradient-to-br from-purple-600 to-violet-700 p-5 text-white shadow-lg shadow-purple-200">
            <p className="text-[10px] font-bold tracking-widest uppercase text-purple-200 mb-3">About</p>
            <p className="text-xs leading-relaxed text-white/85 mb-4">
              Ask questions about Nepali law. Powered by a fine-tuned Qwen2.5 SLM with HyDE retrieval and RAG.
            </p>
            <div className="space-y-2 text-[11px] text-purple-200">
              {['SLM generates hypothetical answer', 'FAISS retrieves real legal passages', 'SLM answers with real context'].map((s, i) => (
                <div key={i} className="flex items-start gap-2">
                  <span className="mt-px w-4 h-4 rounded bg-white/15 text-white text-[9px] font-bold flex items-center justify-center flex-shrink-0">
                    {i + 1}
                  </span>
                  <span className="leading-tight">{s}</span>
                </div>
              ))}
            </div>
          </div>
          <div className="rounded-2xl bg-white border border-purple-100 p-4 shadow-sm">
            <p className="text-[10px] font-bold tracking-widest uppercase text-gray-300 mb-3">Try These</p>
            <div className="space-y-0.5">
              {SAMPLES.map(q => (
                <button key={q} onClick={() => { setQuestion(q); textareaRef.current?.focus() }}
                  disabled={loading}
                  className="w-full text-left text-[12px] text-gray-500 px-2.5 py-2 rounded-lg hover:bg-purple-50 hover:text-purple-700 transition-colors disabled:opacity-40 leading-snug">
                  {q}
                </button>
              ))}
            </div>
          </div>
          {history.length > 0 && (
            <div className="rounded-2xl bg-white border border-purple-100 p-4 shadow-sm">
              <p className="text-[10px] font-bold tracking-widest uppercase text-gray-300 mb-3">Recent</p>
              <div className="space-y-0.5">
                {history.map((h, i) => (
                  <button key={i} onClick={() => { setQuestion(h.question); textareaRef.current?.focus() }}
                    disabled={loading}
                    className="w-full text-left px-2.5 py-2 rounded-lg hover:bg-purple-50 transition-colors disabled:opacity-40 group">
                    <p className="text-[12px] text-gray-500 group-hover:text-purple-600 truncate leading-snug">{h.question}</p>
                    <p className="text-[10px] text-gray-300 mt-0.5">{h.time}</p>
                  </button>
                ))}
              </div>
            </div>
          )}
        </aside>

        <main className="space-y-4 min-w-0">
          <div className="bg-white rounded-2xl border border-purple-100 shadow-sm overflow-hidden">
            <div className="px-5 pt-5 pb-3">
              <div className="flex items-center justify-between gap-3 mb-3">
                <p className="text-[10px] font-bold tracking-widest uppercase text-gray-300">Your Question</p>
              </div>
              <textarea
                ref={textareaRef}
                rows={1}
                value={question}
                onChange={e => setQuestion(e.target.value)}
                onKeyDown={handleKey}
                disabled={loading}
                placeholder="नेपाली वा अंग्रेजीमा प्रश्न सोध्नुहोस्… (Ask in Nepali or English)"
                className="w-full resize-none text-sm text-gray-800 placeholder-gray-500 bg-transparent outline-none leading-relaxed disabled:opacity-50"
                style={{ minHeight: '44px', maxHeight: '160px', overflowY: 'auto' }}
              />
            </div>
            <div className="px-4 pb-4 pt-2 border-t border-purple-50 flex items-center justify-between gap-3">
              <p className="text-[11px] text-gray-300 hidden sm:block">
                <kbd className="font-mono bg-gray-100 text-gray-400 px-1 py-px rounded text-[10px]">Enter</kbd> to send
              </p>
              <button
                onClick={() => handleSubmit()}
                disabled={loading || !question.trim()}
                className="ml-auto flex items-center gap-2 bg-purple-600 hover:bg-purple-700 active:bg-purple-800 disabled:bg-purple-200 text-white text-xs font-semibold px-4 py-2 rounded-lg transition-colors cursor-pointer disabled:cursor-not-allowed select-none"
              >
                {loading
                  ? <><Spinner /><span>Processing…</span></>
                  : <><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="22" y1="2" x2="11" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></svg><span>Ask</span></>
                }
              </button>
            </div>
          </div>

          {error && (
            <div className="flex items-start gap-3 bg-red-50 border border-red-200 rounded-xl p-4">
              <svg className="text-red-400 flex-shrink-0 mt-0.5" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z"/>
                <line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/>
              </svg>
              <div>
                <p className="text-sm font-semibold text-red-700 mb-0.5">Request failed</p>
                <p className="text-xs text-red-500">{error}</p>
                <p className="text-xs text-red-400 mt-1">Check that `VITE_API_BASE` points to your running backend.</p>
              </div>
            </div>
          )}

          {loading && <LoadingView phase={phase} />}

          {mode === 'single' && result && !loading && (
            <div ref={resultsRef} className="space-y-3" style={{ animation: 'fadeUp 0.35s ease' }}>
              <div className="flex items-center justify-between px-1 py-1">
                <p className="text-xs font-semibold text-gray-700">
                  Results
                  <span className="font-normal text-gray-400 ml-2 italic">"{result.question.slice(0, 60)}{result.question.length > 60 ? '…' : ''}"</span>
                </p>
                <span className="text-[11px] text-gray-400 font-mono flex-shrink-0">{result.processing_time}s</span>
              </div>
              <HydeCard passage={result.hyde_passage} />
              <DocsCard docs={result.retrieved_docs} />
              <AnswerCard answer={result.answer} />
            </div>
          )}

          {!loading && !result && !error && (
            <div className="flex flex-col items-center justify-center py-20 px-8 text-center">
              <div className="w-12 h-12 rounded-2xl bg-purple-100 flex items-center justify-center mb-4">
                <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#7c3aed" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M12 1L3 5v6c0 5.25 3.75 10.15 9 11.35C17.25 21.15 21 16.25 21 11V5L12 1z"/>
                </svg>
              </div>
              <p className="text-sm font-semibold text-gray-600 mb-1">Ask about Nepali law</p>
              <p className="text-xs text-gray-400 max-w-xs leading-relaxed">
                Rights, acts, procedures, regulations — answered with grounded legal context.
              </p>
            </div>
          )}

        </main>
      </div>

      <footer className="border-t border-purple-100 bg-white">
        <div className="max-w-5xl mx-auto px-5 h-10 flex items-center justify-between">
          <span className="text-[11px] text-gray-500">Dipsan99 · HyDE-RAG · zeri000/nepali_legal_qwen_merged_4</span>
          <div className="flex items-center gap-4">
            <a href="https://huggingface.co/zeri000/nepali_legal_qwen_merged_4" target="_blank" rel="noreferrer"
              className="text-[11px] text-gray-500 hover:text-purple-600 transition-colors">Model</a>
            <a href="https://huggingface.co/datasets/zeri000/augmented_nepali_legal_qa.csv" target="_blank" rel="noreferrer"
              className="text-[11px] text-gray-500 hover:text-purple-600 transition-colors">Dataset</a>
          </div>
        </div>
      </footer>

      <style>{`
        @keyframes fadeUp {
          from { opacity: 0; transform: translateY(10px); }
          to   { opacity: 1; transform: translateY(0); }
        }
      `}</style>
    </div>
  )
}
